// This file is generated by icon spritesheet generator

export const iconNames = ["Width", "Version", "Polygon", "Namespace", "Multi", "Empty", "Circle"] as const

export type IconName = (typeof iconNames)[number]
